---
- hosts: salt-master
  become: true
  tasks:

    - name: Add nested repos
      ansible.builtin.shell: '{{ item }}'
      with_items:
        - sudo rpm --import https://repo.saltproject.io/salt/py3/redhat/7/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub
        - curl -fsSL https://repo.saltproject.io/salt/py3/redhat/7/x86_64/3006.repo | sudo tee /etc/yum.repos.d/salt.repo 

    - name: Install salt-master
      ansible.builtin.yum:
        name: salt-master 
        state: present
        update_cache: true

    - name: Start master
      ansible.builtin.service:
        name: salt-master
        state: started
        enabled: true

    - name: Generete ssh keypair
      ansible.builtin.openssh_keypair:
        path: /home/vagrant/.ssh/id_ssh_rsa
        owner: vagrant
        group: vagrant

    - name: Append additional host entries to /etc/hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "192.168.56.215 salt"
        - "192.168.56.216 salt-minion1"
        - "192.168.56.217 salt-minion2"
  
    - name: Create root salt dir
      ansible.builtin.file:
        path: /srv/salt
        state: directory

    - name: Copy files
      ansible.builtin.copy:
        src: formulas/
        dest: /srv/salt/
      notify: restart salt-master

  handlers:
    - name: restart salt-master
      ansible.builtin.service:
        name: salt-master
        state: restarted
  
- hosts: salt-minion1,salt-minion2
  become: true
  tasks:
    - name: Add nested repos
      ansible.builtin.shell: '{{ item }}'
      with_items:
        - sudo rpm --import https://repo.saltproject.io/salt/py3/redhat/7/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub
        - curl -fsSL https://repo.saltproject.io/salt/py3/redhat/7/x86_64/3006.repo | sudo tee /etc/yum.repos.d/salt.repo

    - name: Install salt-minion
      ansible.builtin.yum:
        name: salt-minion 
        state: present
        update_cache: true
  
    - name: Start salt-minion
      ansible.builtin.service:
        name: salt-minion
        state: started
        enabled: true

    - name: Modify sshd_config
      ansible.builtin.shell: |
        sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config; systemctl restart sshd
  
    - name: Append additional host entries to /etc/hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "192.168.56.215 salt"
        - "192.168.56.216 salt-minion1"
        - "192.168.56.217 salt-minion2"
