---
- name: Install podman lvm2
  ansible.builtin.dnf:
    name:
      - podman
      - lvm2
    state: latest

- name: Start podman service
  ansible.builtin.systemd:
    name: podman
    state: restarted
    enabled: yes

- name: Download cephadm
  ansible.builtin.get_url:
    url: https://download.ceph.com/rpm-18.2.0/el9/noarch/cephadm
    dest: ~/cephadm
    mode: '0755'

- name: Install ceph
  ansible.builtin.command: "{{ item }}"
  loop:
    - ~/cephadm add-repo --release reef
    - ~/cephadm install
    - ~/cephadm install ceph-common

- name: Remove file cephadm
  ansible.builtin.file:
    path: ~/cephadm
    state: absent