- name: Install python flask backend
  hosts: backend
  become: true
  gather_facts: true
  tasks:

    - name: Install required packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-devel
        - libpq-devel
        - gcc
      
    - name: Install pip required packages
      ansible.builtin.pip:
        name:
          - flask
          - Flask-SQLAlchemy
          - psycopg2
          - wheel

    - name: Copy application files
      ansible.builtin.template:
        src: app.j2
        dest: app.py
        owner: almalinux
        group: almalinux
        mode: 0755

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: flask_app.service
        dest: /etc/systemd/system/flask_app.service

    - name: Enable and start the service
      ansible.builtin.systemd:
        name: flask_app.service
        enabled: yes
        state: started

    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present
        
    - name: Create nginx configuration file for static content
      ansible.builtin.template:
        src: nginx_static.conf.j2
        dest: /etc/nginx/conf.d/static.conf
        owner: root
        group: root
        mode: '0644'
        
    - name: Remove default configuration from sites-enabled
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
    
    - name: Add static page
      ansible.builtin.copy:
        src: index.html
        dest: /mnt/www/html/

    - name: Disable SE linux
      ansible.builtin.command: chcon -R -t httpd_sys_content_t /mnt/www/html/

    - name: Restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted