---
- name: Install consul agent
  hosts: nginx
  become: true
  gather_facts: true
  vars_files: vars/main.yml
  tasks:

    - name: Append additional host entries to /etc/hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "10.0.1.3 nginx1 consul-nginx1"
        - "10.0.1.4 nginx2 consul-nginx1"
        - "10.0.1.5 backend1"
        - "10.0.1.6 backend2"
        - "10.0.1.7 pgdb1 consul1"
        - "10.0.1.8 pgdb2 consul2"
        - "10.0.1.9 pgdb3 consul3"

    - name: Install unzip
      ansible.builtin.apt:
        name: 
          - unzip
          - curl
        state: present

    - name: Download Consul
      ansible.builtin.get_url:
        url: https://hashicorp-releases.yandexcloud.net/consul/1.19.1/consul_1.19.1_linux_amd64.zip
        dest: /tmp/consul.zip

    - name: Unzip Consul
      ansible.builtin.unarchive:
        src: /tmp/consul.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Set executable permissions
      ansible.builtin.file:
        path: /usr/local/bin/consul
        mode: '0755'

    - name: Create Consul user
      ansible.builtin.user:
        name: consul
        system: yes
        shell: /bin/false

    - name: Create directories for Consul
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: consul
        group: consul
        mode: '0755'
      loop:
        - /etc/consul.d
        - /opt/consul

    - name: Create Consul configuration file
      ansible.builtin.template:
        src: consul-agent.hcl.j2
        dest: /etc/consul.d/consul.hcl
       
    - name: Copy service web config for consul
      ansible.builtin.template:
        src: consul-web.j2
        dest: /etc/consul.d/web.json
        
    - name: Create systemd service file for Consul
      ansible.builtin.copy:
        dest: /etc/systemd/system/consul.service
        content: |
          [Unit]
          Description=Consul Agent
          Documentation=https://www.consul.io/docs
          Requires=network-online.target
          After=network-online.target

          [Service]
          User=consul
          Group=consul
          ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Consul service
      ansible.builtin.systemd:
        name: consul
        state: started
        enabled: yes