---
- name: Install consul server
  hosts: db
  become: true
  gather_facts: true
  vars_files: vars/main.yml
  tasks:

    - name: Install required packages
      ansible.builtin.apt:
        name: 
          - unzip
          - curl
        state: present
    
    - name: Append additional host entries to /etc/hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "10.0.1.3 nginx1 consul-nginx1"
        - "10.0.1.4 nginx2 consul-nginx1"
        - "10.0.1.5 backend1"
        - "10.0.1.6 backend2"
        - "10.0.1.7 pgdb1 consul1"
        - "10.0.1.8 pgdb2 consul2"
        - "10.0.1.9 pgdb3 consul3"

    - name: Download consul
      ansible.builtin.get_url:
        url: https://hashicorp-releases.yandexcloud.net/consul/1.19.1/consul_1.19.1_linux_amd64.zip
        dest: /tmp/consul.zip

    - name: Unpack consul
      ansible.builtin.unarchive:
        src: /tmp/consul.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Change permissions
      ansible.builtin.file:
        path: /usr/local/bin/consul
        mode: '0755'

    - name: Create Consul user
      ansible.builtin.user:
        name: consul
        system: yes
        shell: /bin/false

    - name: Create directories for Consul
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: consul
        group: consul
        mode: '0755'
      loop:
        - /etc/consul.d
        - /opt/consul

    - name: Create config
      ansible.builtin.template:
        src: consul.hcl.j2
        dest: /etc/consul.d/consul.hcl

    - name: Create systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/consul.service
        content: |
          [Unit]
          Description=Consul
          Documentation=https://www.consul.io/docs
          Requires=network-online.target
          After=network-online.target

          [Service]
          ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d
          ExecReload=/bin/kill -HUP $MAINPID
          KillMode=process
          Restart=on-failure
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Start consul
      ansible.builtin.systemd:
        name: consul
        state: restarted
        enabled: yes
        daemon_reload: true
