---
- name: Install GFS2
  hosts: gfs2
  become: true
  gather_facts: true
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install lvm and gfs2
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - lvm2
        - gfs2-utils
    
- name: Configure GFS2
  hosts: gfs2-master
  become: true
  gather_facts: true
  tasks:

    - name: Configure DLM CLVM and create FS
      ansible.builtin.command: "{{ item }}"
      with_items:
        - pcs property set stonith-enabled=false
        - pcs property set no-quorum-policy=freeze
        - pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
        - pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
        - pcs constraint order start dlm-clone then clvmd-clone
        - pcs status resources
        - pvcreate /dev/vdb
        - vgcreate -Ay -cy cluster_vg /dev/vdb
        - lvcreate -L5G -n cluster_lv cluster_vg
        - mkfs.gfs2 -j3 -p lock_dlm -t otusha:gfs2 /dev/cluster_vg/cluster_lv
        - pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=ignore clone interleave=true
        - pcs constraint order start clvmd-clone then clusterfs-clone
        - pcs constraint colocation add clusterfs-clone with clvmd-clone
    
