---
- name: Install nginx
  hosts: nginx
  become: true
  gather_facts: true
  tasks:

    - name: Set a hostname
      ansible.builtin.hostname:
        name: nginx1
      when: ansible_host == "{{ groups['nginx'][0] }}"

    - name: Set a hostname
      ansible.builtin.hostname:
        name: nginx1
      when: ansible_host == "{{ groups['nginx'][1] }}"

    - name: Append additional host entries to /etc/hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "10.0.1.3 nginx1 consul-nginx1"
        - "10.0.1.4 nginx2 consul-nginx1"
        - "10.0.1.5 backend1"
        - "10.0.1.6 backend2"
        - "10.0.1.7 pgdb1 consul1"
        - "10.0.1.8 pgdb2 consul2"
        - "10.0.1.9 pgdb3 consul3"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    
    - name: Copy config file
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Enable and start Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
    
    - name: Restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted