---
- name: Install nginx
  hosts: nginx
  become: true
  gather_facts: true
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    
    - name: Copy config file
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Enable and start Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
    
    - name: Restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted