---
- name: Install Nginx
  ansible.builtin.import_playbook: nginx.yml

- name: Install PGSQL
  ansible.builtin.import_playbook: db.yml

- name: Install python flask backend
  ansible.builtin.import_playbook: backend.yml

- name: Install OpenSearch
  hosts: elk
  gather_facts: true
  become: true
  roles:
    - { role: linux/opensearch }

- name: Install OpenSearch dashboards
  hosts:  "{{ groups['elk'][0] }}"
  gather_facts: true
  become: true
  roles:
    - { role: linux/dashboards }

- name: Install vector
  ansible.builtin.import_playbook: vector.yml