---
- name: Install NGINX
  ansible.builtin.import_playbook: 1-nginx.yml

- name: Install PostgreSQL
  ansible.builtin.import_playbook: 2-db.yml

- name: Install ISCSI-target
  ansible.builtin.import_playbook: 3-iscsi-target.yml

- name: Install ISCSI-initiator
  ansible.builtin.import_playbook: 4-iscsi-initiator.yml

- name: Install Pacemaker
  ansible.builtin.import_playbook: 5-pacemaker.yml

- name: Install gfs2
  ansible.builtin.import_playbook: 6-gfs2.yml

- name: Install backend
  ansible.builtin.import_playbook: 7-backend.yml